const LANGUAGE_ICONS: Record<string, string> = {
  Astro: "vscode-icons:file-type-astro",
  Assembly: "vscode-icons:file-type-assembly",
  C: "vscode-icons:file-type-c",
  "C#": "vscode-icons:file-type-csharp",
  "C++": "vscode-icons:file-type-cpp",
  Clojure: "vscode-icons:file-type-clojure",
  CMake: "vscode-icons:file-type-cmake",
  CoffeeScript: "vscode-icons:file-type-coffeescript",
  CSS: "vscode-icons:file-type-css",
  Dart: "vscode-icons:file-type-dartlang",
  Dockerfile: "vscode-icons:file-type-docker",
  Elixir: "vscode-icons:file-type-elixir",
  "F#": "vscode-icons:file-type-fsharp",
  GDScript: "vscode-icons:file-type-gdscript",
  Go: "vscode-icons:file-type-go",
  Groovy: "vscode-icons:file-type-groovy",
  Haxe: "vscode-icons:file-type-haxe",
  HTML: "vscode-icons:file-type-html",
  Java: "vscode-icons:file-type-java",
  JavaScript: "vscode-icons:file-type-js-official",
  JSON: "vscode-icons:file-type-json-official",
  "Jupyter Notebook": "vscode-icons:file-type-jupyter",
  Kotlin: "vscode-icons:file-type-kotlin",
  Lua: "vscode-icons:file-type-lua",
  Markdown: "vscode-icons:file-type-markdown",
  MDX: "vscode-icons:file-type-mdx",
  Mermaid: "vscode-icons:file-type-mermaid",
  Nunjucks: "vscode-icons:file-type-nunjucks",
  "Objective-C": "vscode-icons:file-type-objectivec",
  Perl: "vscode-icons:file-type-perl",
  PHP: "vscode-icons:file-type-php",
  PowerShell: "vscode-icons:file-type-powershell",
  Python: "vscode-icons:file-type-python",
  QML: "vscode-icons:file-type-qml",
  Ruby: "vscode-icons:file-type-ruby",
  Rust: "vscode-icons:file-type-rust",
  Scala: "vscode-icons:file-type-scala",
  SCSS: "vscode-icons:file-type-scss",
  Shell: "vscode-icons:file-type-shell",
  SVG: "vscode-icons:file-type-svg",
  Svelte: "vscode-icons:file-type-svelte",
  Swift: "vscode-icons:file-type-swift",
  TypeScript: "vscode-icons:file-type-typescript-official",
  "Vim Script": "vscode-icons:file-type-vim",
  "Vim script": "vscode-icons:file-type-vim",
  Vue: "vscode-icons:file-type-vue",
  Zig: "vscode-icons:file-type-zig",
};

export function getLanguageIcon(language: string | null): string | null {
  return language ? LANGUAGE_ICONS[language] ?? null : null;
}
